apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: hello-python
    version: tagver
    env: environment
